import '../styles/globals.css'
import React from 'react';
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ThemeProvider from '@/components/provider/themeProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ThemeProvider>
            <div>{children}</div>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
